feat: Implement dotnet6
nventive/Chinook.DataLoader pull request #44
Opened 2022-09-21 14:38 UTC by lamonfly

GitHub Issue: #

## Proposed Changes

 - [ ] Bug fix
 - [X] Feature
 - [ ] Code style update (formatting)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build or CI related changes
 - [ ] Documentation content changes
 - [ ] Other, please describe:

## What is the current behavior?

## What is the new behavior?

Added support of dotnet6

## Impact on version

- [ ] **Major** (Public API was modified.)
  - Public constructs (class, struct, delegate, enum, etc.) were removed or renamed.
  - Public members were removed or renamed.
  - Public method signatures were changed or renamed.
- [X] **Minor** (Public API was extended.)
  - Public constructs, members, or overloads were added.
- [ ] **Patch** (Public API was unchanged.)
  - A bug in behavior was fixed.
  - Documentation was changed.
- [ ] **None** (The library is unchanged.)
  - Only code under the `build` folder was changed.
  - Only code under the `.github` folder was changed.

## Checklist

Please check that your PR fulfills the following requirements:

- [X] Documentation has been added/updated.
- [ ] Automated Unit / Integration tests for the changes have been added/updated.
- [ ] Updated [BREAKING_CHANGES.md](../BREAKING_CHANGES.md) (if you introduced a breaking change).
- [ ] Your conventional commits are aligned with the **Impact on version** section.

## Other information

2022-09-21 20:45 UTC, jeanplevesque requested changes

2022-09-21 20:45 UTC, jeanplevesque commented on src/DataLoader.Uno.WinUI/DataLoaderView.cs
> +﻿using Microsoft.UI.Xaml;
Could we share code for `DataLoaderView `and `DataLoaderViewController` using global usings and base classes?

2022-09-21 20:45 UTC, jeanplevesque commented on src/DataLoader.Uno/DataLoader.Uno.csproj
>  		<TargetFrameworks Condition="'$([MSBuild]::IsOsPlatform(OSX))'">netstandard2.0;xamarinios10;</TargetFrameworks>
You probably want to apply the same changes as @carlh98 did on other packages.

2022-09-21 20:45 UTC, jeanplevesque commented on src/DataLoader.Uno/DataLoader.Uno.csproj
>  		<TargetFrameworks Condition="'$([MSBuild]::IsOsPlatform(OSX))'">netstandard2.0;xamarinios10;</TargetFrameworks>
Like 
- target frameworks
- tags

2022-09-21 20:45 UTC, jeanplevesque commented on DataLoader.sln
>  ﻿
Make sure you also update the documentation (in readme).

2022-09-22 13:05 UTC, jeanplevesque requested changes

2022-09-22 13:05 UTC, jeanplevesque commented on src/DataLoader.Uno.WinUI/DataLoader.Uno.WinUI.csproj
> +		<TargetFrameworks Condition="'$([MSBuild]::IsOsPlatform(OSX))'">netstandard2.0;net6.0-ios;net6.0-maccatalyst;net6.0-macos</TargetFrameworks>
I think those are incorrect. Check with @carlh98

2022-09-22 13:05 UTC, jeanplevesque commented on src/DataLoader.Uno.WinUI/DataLoader.Uno.WinUI.csproj
> +		<PackageTags>dataloader;async;mvvm;xamarin;ios;android;uwp;chinook</PackageTags>
please add **maui** and **winui** to this list of tags in **all csproj files** (except tests 😉)

2022-09-22 17:55 UTC, jeanplevesque approved these changes

2022-09-22 18:08 UTC, carlh98 approved these changes

2022-09-22 18:14 UTC, merged