feat: implemented workaround for Uno.Toolkit.UI error
nventive/Chinook.DataLoader pull request #49
Opened 2023-10-30 18:38 UTC by ryanwin98

GitHub Issue: #

## Proposed Changes

 - [x] Bug fix
 - [ ] Feature
 - [ ] Code style update (formatting)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build or CI related changes
 - [ ] Documentation content changes
 - [ ] Other, please describe:

## What is the current behavior?
Currently when upgrading a project to Uno 5 the following message is displayed:
![image](https://github.com/nventive/Chinook.DataLoader/assets/104783204/3a8e24cc-8998-428f-84fd-0a145d011501)

## What is the new behavior?
Workaround implemented avoids including Uno.Toolkit.UI XBFs in the PRI file

## Impact on version

- [ ] **Major** (Public API was modified.)
  - Public constructs (class, struct, delegate, enum, etc.) were removed or renamed.
  - Public members were removed or renamed.
  - Public method signatures were changed or renamed.
- [ ] **Minor** (Public API was extended.)
  - Public constructs, members, or overloads were added.
- [ ] **Patch** (Public API was unchanged.)
  - A bug in behavior was fixed.
  - Documentation was changed.
- [ ] **None** (The library is unchanged.)
  - Only code under the `build` folder was changed.
  - Only code under the `.github` folder was changed.

## Checklist

Please check that your PR fulfills the following requirements:

- [ ] Documentation has been added/updated.
- [ ] Automated Unit / Integration tests for the changes have been added/updated.
- [ ] Updated [BREAKING_CHANGES.md](../BREAKING_CHANGES.md) (if you introduced a breaking change).
- [ ] Your conventional commits are aligned with the **Impact on version** section.

## Other information
Currently a WIP as the investigation continues to locate all the packages that cause this exception to be thrown

2023-10-30 20:12 UTC, jeanplevesque requested changes

2023-10-30 20:12 UTC, jeanplevesque commented on winappsdk-workaround.targets
> +<Project>
If this file is specific to WinUI, can we move it under the WinUI directory instead of having it at the root of the repository?

2023-11-01 19:32 UTC, Soap-141 approved these changes

2023-11-01 19:58 UTC, carlh98 approved these changes

2023-11-02 15:06 UTC, Soap-141 approved these changes

2023-11-02 18:51 UTC, merged